budgetwebapp/budget/urls.py
from django.urls import path

from .views import (
    transactions_list_view,
    transaction_add,
    transaction,
    transaction_edit,
    transaction_delete,
    incoming_transactions_list_view,
    outgoing_transactions_list_view,
    monthly_expense_summary_view,
    monthly_income_summary_view,
    yearly_expense_summary_view,
    chart_summary,
    BalanceHistoryAPIView,
    balance_history_view,
    duplicate_transaction,
    refresh_balance_history,
)

from api.views import (
    TransactionsAPIView,
    TransactionAPIView,
    TransactionFormAPIView,
    ChartDataAPIView,
    BalanceHistoryRefreshAPIView,
)

from rest_framework import permissions
from drf_yasg.views import get_schema_view
# from rest_framework.schemas import get_schema_view  # openAPI  # https://www.django-rest-framework.org/api-guide/schemas/
# from rest_framework_swagger.views import get_swagger_view  # django-rest-swagger
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Your API Title",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # 1. Get Transactions
    path('transactions/', transactions_list_view, name='transactions'),
    # 2. Create a new Transaction
    path('transactions/add/', transaction_add, name='transaction_add'),
    # 3. Get Transaction
    path('transactions/<int:transaction_id>/', transaction, name='transaction'),
    # 4. Update the Transaction
    path('transactions/<int:transaction_id>/edit/', transaction_edit, name='transaction_edit'),
    # 5. Delete the Transaction
    path('transactions/<int:transaction_id>/delete/', transaction_delete, name='transaction_delete'),
    # 6. Duplicate Transaction
    path('transactions/duplicate/<int:transaction_id>/', duplicate_transaction, name='duplicate_transaction'),
    # 7. Incoming Transactions List
    path('transactions/incoming/', incoming_transactions_list_view, name='incoming_transactions'),
    # 8. Outgoing Transactions List
    path('transactions/outgoing/', outgoing_transactions_list_view, name='outgoing_transactions'),
    # 9. Monthly Expense Summary
    path('transactions/monthly-expense-summary/', monthly_expense_summary_view, name='monthly_expense_summary'),
    # 10. Monthly Income Summary
    path('transactions/monthly-income-summary/', monthly_income_summary_view, name='monthly_income_summary'),
    # 11. Yearly Summary
    path('transactions/yearly-expense-summary/', yearly_expense_summary_view, name='yearly_expense_summary'),
    # 12. Charts view
    path('transactions/chart-summary/', chart_summary, name='chart_summary'),
    # 13. Balance History View
    path('balance-history/<str:money_account_name>/', balance_history_view, name='balance_history'),
    # 14. Balance History Refresh
    path('balance-history/refresh/<str:money_account_name>/', refresh_balance_history, name='balance_history_refresh'),

]

urlpatterns = urlpatterns + [
    # 1. Get Transactions
    path('api/transactions/', TransactionsAPIView.as_view(), name='transactions_api'),
    # 2. Create a new Transaction
    path('api/transactions/', TransactionsAPIView.as_view(), name='transaction_add_api'),
    # 3. Get Transaction
    path('api/transactions/<int:transaction_id>/', TransactionAPIView.as_view(), name='transaction_api'),
    # 4. Update the Transaction
    path('api/transactions/<int:transaction_id>/', TransactionAPIView.as_view(), name='transaction_update_api'),
    # 5. Delete the Transaction
    path('api/transactions/<int:transaction_id>/', TransactionAPIView.as_view(), name='transaction_delete_api'),
    # 6. Duplicate Transaction

    # 7. Incoming Transactions List

    # 8. Outgoing Transactions List

    # 9. Monthly Expense Summary

    # 10. Monthly Income Summary

    # 11. Yearly Summary

    # 12. Charts view
    path('api/chart-data/', ChartDataAPIView.as_view(), name='chart-data'),
    # 13. Balance History View
    path('api/balance-history/<str:money_account_name>/', BalanceHistoryAPIView.as_view(), name='balance-history-api'),
    # 14. Balance History Refresh
    path('api/balance-history/refresh/<str:money_account_name>/', BalanceHistoryRefreshAPIView.as_view(), name='balance-history-refresh-api'),

    # 4.2. Edit Transaction Form
    # path('api/transactions/form/<int:transaction_id>/', TransactionFormAPIView.as_view(), name='transaction_form_api'),  # todo: create a separate, better suited form

    # API DOCS
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='api_docs'),
    # path('openapi', get_schema_view(title="Your Project", description="API for all things …"), name='openapi-schema'),
    # path('api/docs/', get_swagger_view(title='Your API Title')),
    # path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

budgetwebapp/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('budget.urls', 'budget'), namespace='budget')),
]

budgetwebapp/budget/forms.py
from django import forms
from django.forms import SelectDateWidget
from .models import Transaction, Category
from django.forms import DateInput


class CustomDateInput(DateInput):
    input_type = 'date'


class BudgetExpenseEntryForm(forms.ModelForm):
    date = forms.DateField(widget=CustomDateInput)
    description = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Transaction
        fields = ['date', 'category', 'amount', 'origin', 'destination', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.all()

budgetwebapp/budget/views.py
import requests
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from rest_framework.exceptions import ValidationError

from api.views import BalanceHistoryAPIView
from .forms import BudgetExpenseEntryForm
from .models import Transaction, MoneyAccount
from .serializers import BalanceHistorySerializer, BalanceHistoryRefreshSerializer
from .summary import create_summary_table, create_yearly_summary
from .utils import get_data_from_form, get_response_by_status_code


# ===============================================
#               BALANCE HISTORY
# ===============================================

def refresh_balance_history(request, money_account_name):
    serializer = BalanceHistoryRefreshSerializer(data={'money_account_name': money_account_name})

    try:  # or just do serializer.is_valid(raise_exception=True) instead of try/except for default handling
        serializer.is_valid(raise_exception=True)
    except ValidationError as e:
        error_message = str(e.detail)
        # Handle the validation error as needed
        # For example, you can return a custom error response
        return HttpResponseBadRequest(error_message)

    message = serializer.create(serializer.validated_data)['message']
    return redirect('budget:balance_history', money_account_name=money_account_name)

    # response = balance_history_view(request, money_account_name=money_account_name)
    # return response


def balance_history_view(request, money_account_name):
    balance_history_api_view = BalanceHistoryAPIView.as_view()
    response = balance_history_api_view(request, money_account_name=money_account_name)
    serializer = BalanceHistorySerializer(data=response.data, many=True)
    serializer.is_valid()
    balance_history = serializer.validated_data

    context = {
        'balance_history': balance_history,
        'money_account_name': money_account_name
    }

    return render(request, 'budget/balance_history.html', context)


# ===============================================
#                    CHARTS
# ===============================================

def chart_summary(request):
    context = {}
    return render(request, 'budget/chart_summary.html', context)


# ===============================================
#               TABLE SUMMARIES
# ===============================================

def yearly_expense_summary_view(request):
    summary, totals = create_yearly_summary(2023)
    expense_summary_detailed, total_expense_summary_detailed = create_summary_table(2023, "expense")
    income_summary_detailed, total_income_summary_detailed = create_summary_table(2023, "income")

    context = {
        'summary': summary,
        'totals': totals,
        'expense_summary_detailed': expense_summary_detailed,
        'total_expense_summary_detailed': total_expense_summary_detailed,
        'income_summary_detailed': income_summary_detailed,
        'total_income_summary_detailed': total_income_summary_detailed
    }

    return render(request, 'budget/yearly_expense_summary.html', context)


def monthly_expense_summary_view(request):
    summary_table, summary_table_total = create_summary_table(2023, "expense")

    context = {
        'summary_table': summary_table,
        'summary_table_total': summary_table_total
    }

    return render(request, 'budget/monthly_expense_summary.html', context)


def monthly_income_summary_view(request):
    summary_table, summary_table_total = create_summary_table(2023, "income")

    context = {
        'summary_table': summary_table,
        'summary_table_total': summary_table_total
    }

    return render(request, 'budget/monthly_income_summary.html', context)


# ===============================================
#        INCOMING / OUTGOING TRANSACTIONS
# ===============================================

def outgoing_transactions_list_view(request):
    entries = Transaction.objects.filter(transaction_type__in=['OUTGOING', 'INNER']).order_by('date')

    paginator = Paginator(entries, 999)  # 10 entries per page
    page_number = request.GET.get('page')
    transactions_page_obj = paginator.get_page(page_number)

    context = {
        'transactions_page_obj': transactions_page_obj
    }

    return render(request, 'budget/transactions_outgoing.html', context)


def incoming_transactions_list_view(request):
    entries = Transaction.objects.filter(transaction_type__in=['INCOMING', 'INNER']).order_by('date')

    paginator = Paginator(entries, 999)  # 10 entries per page
    page_number = request.GET.get('page')
    transactions_page_obj = paginator.get_page(page_number)

    context = {
        'transactions_page_obj': transactions_page_obj
    }

    return render(request, 'budget/transactions_incoming.html', context)


# ===============================================
#                 CRUD + DUPLICATE
# ===============================================


def transactions_list_view(request):
    if request.method == 'GET':
        api_url = request.build_absolute_uri(reverse('budget:transactions_api'))  # API endpoint URL
        response = requests.get(api_url)
        transactions = get_response_by_status_code(response, 200, response.json(), [])

        mountAccounts = MoneyAccount.objects.all().aggregate(total=Sum('balance'))['total']
        paginator = Paginator(transactions, 999)  # 10 entries per page
        page_number = request.GET.get('page')
        transactions_page_obj = paginator.get_page(page_number)

        context = {
            'transactions_page_obj': transactions_page_obj,
            'sum_accs': round(mountAccounts, 2)
        }

        return render(request, 'budget/transactions.html', context)


def duplicate_transaction(request, transaction_id):
    # Get the existing transaction entry
    existing_transaction = Transaction.objects.get(id=transaction_id)

    if request.method == 'POST':
        # Create a form instance with the POST data
        form = BudgetExpenseEntryForm(request.POST)
        if form.is_valid():
            # Save the duplicated entry
            new_transaction = form.save(commit=False)
            new_transaction.pk = None  # Clear the primary key to create a new entry
            new_transaction.save()

            return HttpResponse(status=204)
    else:
        if not ('HX-Request' in request.headers):
            # Redirect users if accessing the URL directly
            return redirect(reverse_lazy('budget:transactions'))

        # Create a form instance with the existing entry data
        form = BudgetExpenseEntryForm(instance=existing_transaction)

    return render(request, 'budget/transaction_add.html', {'form': form})


def transaction_add(request):
    if request.method == 'POST':

        form = BudgetExpenseEntryForm(request.POST)

        if form.is_valid():
            api_url = request.build_absolute_uri(reverse('budget:transaction_add_api'))
            response = requests.post(api_url, data=get_data_from_form(form))
            return get_response_by_status_code(response, 204, HttpResponse(status=204), HttpResponseBadRequest())

    else:
        if not ('HX-Request' in request.headers):
            # Redirect users if accessing the URL directly
            return redirect(reverse_lazy('budget:transactions'))

        form = BudgetExpenseEntryForm()
    return render(request, 'budget/transaction_add.html', {'form': form})


def transaction(request, transaction_id):
    if request.method == 'GET':
        api_url = request.build_absolute_uri(reverse('budget:transaction_api', args=[transaction_id]))  # API endpoint URL
        response = requests.get(api_url)
        transactions = get_response_by_status_code(response, 200, response.json(), [])

        transactions = [transactions]
        paginator = Paginator(transactions, 999)  # 10 entries per page
        page_number = request.GET.get('page')
        transactions_page_obj = paginator.get_page(page_number)

        context = {
            'transactions_page_obj': transactions_page_obj,
        }

        return render(request, 'budget/transactions.html', context)


def transaction_edit(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)

    if request.method == 'POST':
        form = BudgetExpenseEntryForm(request.POST, instance=transaction)

        if form.is_valid():
            api_url = request.build_absolute_uri(reverse('budget:transaction_update_api', args=[transaction_id]))
            response = requests.put(api_url, data=get_data_from_form(form))
            return get_response_by_status_code(response, 200, HttpResponse(status=200), HttpResponseBadRequest())

    else:
        if not ('HX-Request' in request.headers):
            return redirect(reverse_lazy('budget:transactions'))

        form = BudgetExpenseEntryForm(instance=transaction)

    return render(request, 'budget/transaction_form.html', {'form': form, 'transaction_id': transaction_id})


def transaction_delete(request, transaction_id):
    api_url = request.build_absolute_uri(reverse('budget:transaction_delete_api', args=[transaction_id]))

    if request.method == 'GET':
        response = requests.delete(api_url)
        return get_response_by_status_code(response, 200, redirect('budget:transactions'))

    return redirect('budget:transactions')

# return render(request, 'confirmation_template.html', {'entry': entry})

budgetwebapp/budget/templates/budget/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS -->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'budget/main.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'budget/bs5_tables.css' %}">


</head>
<body>

    {% include 'budget/navbar.html' with page_obj=page_obj %}

    {% block content %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.min.js" integrity="sha512-a6ctI6w1kg3J4dSjknHj3aWLEbjitAXAjLDRUxo2wyYmDFRcz2RJuQr5M3Kt8O/TtUSp8n2rAyaXYy1sjoKmrQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.min.js" integrity="sha512-3dZ9wIrMMij8rOH7X3kLfXAzwtcHpuYpEgQg1OA4QAob1e81H8ntUQmQm3pBudqIoySO5j0tHN4ENzA6+n2r4w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://unpkg.com/htmx.org@1.9.2"></script>

    <script defer src="{% static 'budget/js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</body>
</html>

budgetwebapp/budget/templates/budget/entries_table.html
{% load static %}
{% load humanize %}
{% load mathfilters %}

<h1>Budget Entry List</h1>

<div class="table-responsive border rounded-2">
    <table class="table table-dark table-hover table-striped align-middle">
        <thead>
        <tr class="align-middle">
            <th><a href="{% url 'budget:budget_entry_add' %}" class="btn btn-primary bi bi-plus"></a></th>
            <th>Index</th>
            <th>Date</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Type</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for entry in page_obj %}
        <tr data-bs-toggle="tooltip" data-bs-placement="top" title="Description: {{ entry.description }}">
            <td class="text-center narrow-column font-size-small">{{ entry.year }}</td>
            <td class="text-center narrow-column font-size-medium">{{ page_obj|length|sub:forloop.counter|add:1 }}</td>
            <td class="nowrap">{{ entry.date }}</td>
            <td class="nowrap">{{ entry.created_at|date:'N d, Y H:i A' }}</td>
            <td class="nowrap">{{ entry.updated_at|date:'N d, Y H:i A' }}</td>
            <td>{{ entry.category }}</td>
            <td>{{ entry.amount }}</td>
            <td>{{ entry.origin }}</td>
            <td>{{ entry.destination }}</td>
            <td>
                {% if entry.transaction_type == 'INCOMING' %}
                    <i class="fas fa-arrow-down text-success"></i>  <!-- Incoming transaction -->
                {% elif entry.transaction_type == 'OUTGOING' %}
                    <i class="fas fa-arrow-up text-warning"></i>  <!-- Outgoing transaction -->
                {% elif entry.transaction_type == 'INNER' %}
                    <i class="fas fa-arrows-alt-h text-light"></i>  <!-- Inner transaction -->
                {% else %}
                    <i class="fas fa-question-circle"></i>  <!-- None-->
                {% endif %}
            </td>
            <td class="nowrap">
                <a href="{% url 'budget:budget_entry_edit' entry.id %}" class="btn btn-outline-primary bi bi-pen" style="font-size: 10px;"></a>
                <a href="{% url 'budget:budget_entry_remove' entry.id %}" class="btn btn-outline-danger bi bi-trash" style="font-size: 10px; margin-left: 10px;"></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!-- Pagination links -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; First</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ page_obj.number }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>

budgetwebapp/budget/templates/budget/entry_add.html
{% extends "budget/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div style="width: 20%; margin-left: 5%; margin-top: 1%; background: lightgrey;">
        <h1>Add Budget Entry</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group" style="width: 80%; margin-left: 10%; margin-right: 10%;">
                {{ form|crispy }}
            </fieldset>
            <button type="submit" class="btn btn-primary">Add Entry</button>
        </form>
    </div>

{% endblock content %}

budgetwebapp/budget/templates/budget/incoming_transactions.html
{% extends "budget/base.html" %}
{% load static %}

{% block content %}

<div style="width: 50%; margin-left: 5%; margin-top: 1%;">
    {% include 'budget/entries_table.html' with page_obj=page_obj %}
</div>

{% endblock content %}

budgetwebapp/budget/templates/budget/transaction_edit.html
{% extends "budget/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <button type="submit">Save Changes</button>
    </form>

    <a href="{% url 'budget:transaction_edit' 3903 %}" class="btn btn-outline-primary bi bi-pen" style="font-size: 10px;" data-bs-toggle="modal" data-bs-target="#exampleModal"></a>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form|crispy }}
                        </fieldset>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

budgetwebapp/budget/templates/budget/transactions_table.html
{% load static %}
{% load humanize %}
{% load mathfilters %}

<h1>Transactions</h1>

<div class="table-responsive border rounded-2">
    <table class="table table-dark table-hover table-striped align-middle">
        <thead>
        <tr class="align-middle">
<!--            <th><a href="{% url 'budget:transaction_add' %}" class="btn btn-primary bi bi-plus"></a></th>-->
            <th><a hx-get="{% url 'budget:transaction_add' %}" hx-target="#dialog" class="btn btn-primary bi bi-plus"></a></th>
            <th>Index</th>
            <th>Date</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Type</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in transactions_page_obj %}
        <tr data-bs-toggle="tooltip" data-bs-placement="top" title="Description: {{ transaction.description }}">
<!--            <td>duplicate</td>-->
            <td class="text-center narrow-column font-size-small" data-bs-toggle="tooltip" data-bs-placement="top" title="Create a copy">
                <a hx-get="{% url 'budget:duplicate_transaction' transaction.id %}" hx-target="#dialog" class="btn btn-outline-primary fa-regular fa-clone"></a>
            </td>
            <td class="text-center narrow-column font-size-medium">{{ transactions_page_obj|length|sub:forloop.counter|add:1 }}</td>
            <td class="nowrap">{{ transaction.date }}</td>
            <td class="nowrap">{{ transaction.created_at }}</td>
            <td class="nowrap">{{ transaction.updated_at }}</td>
            <td class="nowrap">{{ transaction.category }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.origin }}</td>
            <td>{{ transaction.destination }}</td>
            <td>
                {% if transaction.transaction_type == 'INCOMING' %}
                    <i class="fas fa-arrow-down text-success"></i>  <!-- Incoming transaction -->
                {% elif transaction.transaction_type == 'OUTGOING' %}
                    <i class="fas fa-arrow-up text-warning"></i>  <!-- Outgoing transaction -->
                {% elif transaction.transaction_type == 'INNER' %}
                    <i class="fas fa-arrows-alt-h text-light"></i>  <!-- Inner transaction -->
                {% else %}
                    <i class="fas fa-question-circle"></i>  <!-- None-->
                {% endif %}
            </td>
            <td class="nowrap">
<!--                <a href="{% url 'budget:transaction_edit' transaction.id %}" class="btn btn-outline-primary bi bi-pen" style="font-size: 10px;"></a>-->
                <a hx-get="{% url 'budget:transaction_edit' transaction.id %}" hx-target="#dialog" class="btn btn-outline-primary bi bi-pen" style="font-size: 10px;"></a>
                <a href="{% url 'budget:transaction_delete' transaction.id %}" class="btn btn-outline-danger bi bi-trash" style="font-size: 10px; margin-left: 10px;"></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!-- Pagination links -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if transactions_page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; First</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ transactions_page_obj.number }}</span>
        </li>

        {% if transactions_page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>

<div id="modal" class="modal fade">
  <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>